name: built_redux
version: 8.0.1
description: A state management library written in dart that enforces immutability
homepage: https://github.com/davidmarne/built_redux
dependencies:
  analyzer: ^4.6.0
  build: ^2.3.0
  built_collection: ^5.1.1
  built_value: ^8.4.0
  source_gen: ^1.2.2
  test: ^1.17.12

dev_dependencies:
  build_runner: ^2.2.0
  build_test: ^2.1.5
  built_value_generator: ^8.4.0
  build_web_compilers: ^3.2.5
  workiva_analysis_options: ^1.2.2

environment:
  sdk: ">=2.12.0 <3.0.0"
